import { Receta } from './receta';

export const Recetas: Receta[] = [
{
    title: "Langostinos cocidos",
    steps: "Lleva a ebullición una cazuela con agua y una hoja de laurel. Una vez que rompa a hervir, deja que el agua hierva durante dos minutos, introduce los langostinos, tapa la cazuela y apaga el fuego. Deja que se cuezan de este modo durante tres minutos. Si usas langostinos congelados, es preferible dejar que se descongelen antes de cocerlos.Después, retíralos del agua para cortar la cocción y evitar que se pasen. Resérvalos.Truco: Si la cantidad de langostinos es mayor, debes cocerlos por tandas para que queden cocidos por igual.Por otro lado, prepara un cuenco con agua y hielo, agrega una cucharada colmada de sal y remueve hasta que quede completamente diluida. Así es como se hacen los langostinos cocidos salados, ya que si añades la sal al agua, al langostino no le da tiempo de absorberla. Deposita los langostinos en el agua con hielo y sal y déjalos durante 10 minutos en remojo. Verás que los langostinos cocidos adquieren un tono rosado muy agradable. Después, solo tendrás que volver a colarlos y secarlos con un papel de cocina.¡Y hasta aquí la elaboración! Puedes servir los langostinos cocidos salados con una copita de cava o un vasito de cerveza y sorprenderte de lo buenos que te han quedado. Siempre serán mejor que comprarlos ya hechos, compruébalo y deja tu comentario. Si te ha gustado la receta de Langostinos cocidos, te sugerimos que entres en nuestra categoría de Recetas de Langostinos.Debes de saber que, aun siendo ligeros en grasas o en hidratos de carbono, los langostinos se deben ingerir de vez en cuando por su alto contenido en ácido úrico y colesterol. Según el Departamento de Agricultura de los Estados Unidos[1], 100 gramos de langostinos cocidos contienen los siguientes valores nutricionales:Puedes preparar miles de platos hechos con estos langostinos cocidos, como brochetas combinadas con piña o champiñón y tomates cherry, ensaladas, platos de pasta, ceviches y hasta rellenos para aguacates o patatas. Así mismo, puedes cocinar los langostinos a la plancha o hacerlos al horno. Si buscas más recetas con langostinos, no te pierdas estas ideas:Sube la foto de tu Receta de Langostinos cocidos",
    ingdts: "8 langostinos frescos o congelados, 1 cucharada sopera de sal , Hielo en cubos, 1 litro de agua fría , 1 hoja de laurel (opcional)",
    image: "https://sealandqualityfoods.com/wp-content/uploads/cooked-2125-shrimp-1.jpg"
},
{
    title: "Ensalada de camarones y aguacate",
    steps: "Pela los camarones y resérvalos en un bol. Puedes hacer la ensalada de camarones y aguacate con camarones cocidos o crudos. En caso de usar camarones crudos, deberás cocinarlos a la plancha o cocerlos.Pela los aguacates y córtalos en cubos o en rodajas, cómo más te guste. Añádelos al bol con los camarones y, para evitar que se oxiden los aguacates, vierte un chorro de zumo de limón y mezcla.Corta los tomates cherry por la mitad y la piña en cubos del mismo tamaño que el aguacate. Añade estos ingredientes al bol para seguir con la elaboración de la ensalada de camarones y aguacate.Truco: Puedes sustituir la piña por otras frutas. Por ejemplo, puedes hacer ensalada de camarones, aguacate y mango, coco o naranja.Agrega la lechuga, mayonesa al gusto, mezcla y sirve. ¡Ya tienes tu ensalada de aguacate y camarones lista! En lugar de mayonesa puedes usar salsa rosa, salsa tártara, vinagreta de miel y mostaza o cualquier otra que te guste. Las posibilidades son infinitas, de manera que te animamos a probar y a decirnos qué salsa has agregado tú. Nosotros hemos servido la ensalada en recipientes individuales, pero también puedes presentarla en una única fuente. Así mismo, en función de si la ensalada será un acompañamiento o un plato único, rendirá para más o menos personas. Como plato único es para dos, mientras que como acompañamiento es para cuatro.Si te ha gustado la receta de Ensalada de camarones y aguacate, te sugerimos que entres en nuestra categoría de Recetas de Ensaladas con pescado.Esta receta de ensalada de aguacate y camarones se puede servir como entrante o como plato único, ya que es completa y nutritiva. Aporta proteínas, fibra, vitaminas, minerales y ácidos grasos omega 3. En caso de querer degustarla para cenar, aconsejamos condimentarla con una salsa más bien ligera o, simplemente, con un poco de aceite de oliva o vinagre balsámico sin azúcar.Si sirves la ensalada como entrante o guarnición, puedes acompañarla con carnes y pescados a la plancha, con hamburguesas, con arroz blanco e, incluso con pasta y mezclarlo todo. Las hamburguesas no tiene por qué ser de carne, también pueden ser vegetales, como las hamburguesas de quinoa, que encajan a la perfección con esta ensalada.Sube la foto de tu Receta de Ensalada de camarones y aguacate",
    ingdts: "100 gramos de camarones cocidos o crudos , 2 aguacates, 1 manojo de tomates cherry , 100 gramos de lechuga , 2 rodajas de piña , mayonesa al gusto, 1 chorro de jugo de limón (opcional) , 1 mango (opcional)",
    image: "https://www.fifteenspatulas.com/wp-content/uploads/2016/10/Lime-Shrimp-Avocado-Salad-Skinnytaste-Cookbook-5-640x427.jpg"
},
{
    title: "Arroz con carne molida",
    steps: "Pica la cebolla en pedacitos pequeños y haz lo mismo con el pimentón y el ajo. Condimenta la carne con sal y pimienta al gusto. Pon aceite en una sartén y, cuando esté caliente, agrega la cebolla, el ajo y el pimentón, deja sofreír unos 5 minutos. Añade la carne molida a la sartén y déjala cocinar por unos 5 minutos más. Truco: Puedes usar carne mixta de cerdo y ternera, pues tiene más sabor. Añade el tomate triturado, los frijoles y el perejil. Mezcla todos los ingredientes y deja cocinando por unos 20 minutos más a fuego medio-bajo. Truco: Si gustas, también puedes añadir un vaso de vinotinto. Cuando esté listo, sirve junto al arroz cocido y disfruta de un delicioso plato de arroz con carne molida.Si te ha gustado la receta de Arroz con carne molida, te sugerimos que entres en nuestra categoría de Recetas de Ternera.El arroz con carne molida es un clásico que siempre cae bien, sobre todo cuando no tenemos mucho tiempo para gastar en la cocina. Para que te queden justo a tu medida, te dejamos algunas sugerencias que puedes usar cuando prepares la carne molida con arroz:Si quieres conocer más recetas de carne molida, no dudes en visitar estas: Sube la foto de tu Receta de Arroz con carne molida",
    ingdts: "1 taza de arroz cocido (175 gramos), 250 gramos de carne molida o picada , 250 gramos de tomate triturado , 200 gramos de frijoles precocidos , 1 cebolla, 1 pimentón, Aceite vegetal, 1 rama de perejil , Sal y pimienta al gusto, 1 ajo",
    image: "https://thewoksoflife.com/wp-content/uploads/2015/12/cantonese-beef-8.jpg"
},
{
    title: "Pasta con shiitake y nata",
    steps: "Calienta en una sartén un chorro de aceite de oliva. Cuando esté caliente, saltea el puerro picado y las setas shiitake troceadas. Cocina durante 2-3 minutos a fuego medio. Si usas shiitake en conserva también deberás cortarlas y saltearlas, mientras que si empleas shiitake deshidratadas primero tendrás que hidratarlas en agua.Truco: Puedes sustituir el puerro por cebolla también picada.Añade el brócoli cocido, mezcla con el puerro y las setas y sigue cocinando. Nosotros hemos hecho el brócoli al vapor con una pizca de sal y lo hemos cortado, pero también podrías hervirlo en agua o cocinarlo al horno.Incorpora la nata y salpimienta al gusto. Cocina la salsa shiitake para pasta durante 1 minuto, añade la pasta cocida, mezcla y deja la preparación al fuego durante un par de minutos más. Nosotros hemos escogido pasta corta, pero también podrías hacer las setas shiitake con espaguetis siguiendo este mismo paso a paso.Truco: Si la salsa se espesa demasiado, añade un poco de leche o caldo de la cocción de la pasta.¡Listo! Ya puedes servir la pasta con shiitake y nata espolvoreando queso parmesano rallado por encima y algunas alcaparras. Esta es una receta muy sencilla y completa, perfecta incluso para tupper o para uno de esos días que no tenemos demasiado tiempo para cocinar. Truco: También puedes servir la pasta con shiitake y nueces picando un puñado de estos frutos secos y espolvoreándolos por encima.Si te ha gustado la receta de Pasta con shiitake y nata, te sugerimos que entres en nuestra categoría de Recetas de Fusilli.Una vez preparada la receta de pasta con hongos shiitake y nata puedes servirla acompañada de otros platos como, por ejemplo, una sencilla ensalada verde. Ahora bien, si lo que te apetece es preparar un menú estilo asiático, te recomendamos revisar estas recetas:Sube la foto de tu Receta de Pasta con shiitake y nata",
    ingdts: "200 gramos de pasta cocida , 200 gramos de setas shitake frescas o en conserva , 1 trozo de puerro picado , 1 taza de brócoli picado y cocido , 200 mililitros de nata (crema de leche) , 1 chorro de aceite de oliva , 1 cucharada sopera de alcaparras (opcional) , 1 puñado de queso parmesano rallado , 1 pizca de pimienta negra , 1 pizca de sal",
    image: "https://media4.s-nbcnews.com/i/newscms/2016_02/930461/pasta-carbonara-tease-today-160111_50deeea52212a0eeeba24fb813cb4546.jpg"
},
{
    title: "Cheesecake de frutos rojos",
    steps: "Prepara la base de la tarta de frutos rojos. Para ello, tritura las galletas con un robot de cocina o metiendo las galletas troceadas en una bolsa de plástico y pasando un rodillo por encima hasta hacerlas migas.Truco: Elige las galletas que más te gusten, pueden ser de canela, jengibre, avena, tipo oreo o la que tengas por casa. Funde la mantequilla en el microondas y mezcla con las migas de galletas hasta conseguir una pasta.Engrasa un molde desmontable redondo de unos 22-24 cm y pon la base de galletas en el fondo. Aprieta con las manos las galletas para que queden bien adheridas a la base. Reserva en la nevera.Precalienta el horno a 150 ºC. En un bol amplio, coloca el queso fresco, la nata, la maicena, los huevos y el azúcar; mezcla bien. Puedes utilizar las varillas de una batidora eléctrica, pero bate solo hasta que estén integrados los ingredientes.Saca el molde de la nevera y vierte con cuidado la mezcla de queso. Hornea a 150 ºC con calor arriba y abajo durante 45 minutos. Pasado el tiempo, apaga el horno y deja que la tarta se enfríe en su interior o, por lo menos, déjala dentro del horno apagado otros 45 minutos. Saca la cheesecake de frutos del bosque y guárdala en la nevera por al menos 4 horas para que enfríe.A la hora de servir, decora con el coulis de frutos rojos por encima y con los frutos rojos frescos. Si no tienes coulis de frutos rojos, puedes prepararlo en la receta del enlace o usar mermelada. Calienta la mermelada con una cucharada de agua en el microondas y estará lista para usar.Si te queda cheesecake de frutos rojos, resérvala en la nevera hasta cuatro días como máximo. ¡Disfruta!Si te ha gustado la receta y la haces, envíanos una foto. También te invito a que visites mi blog Cakes para ti.Si te ha gustado la receta de Cheesecake de frutos rojos, te sugerimos que entres en nuestra categoría de Recetas de Tartas.Aunque muchos piensan que las cheesecakes son originarias de Estados Unidos, no hay nada más lejos de la realidad, pues las primeras tartas de queso ya eran cocinadas en la antigua Roma. Por aquel entonces, solo se calentaba el queso troceado con miel y harina, y se dejaba enfriar para servirlo de esta forma. Los antiguos griegos fueron quienes introdujeron los huevos a la mezcla y solo comenzó a parecerse a la tarta de queso que actualmente conocemos cuando llegó a Europa.Hoy en día, podemos hacer la preparación de las tartas de queso más fácil con el uso de queso tipo Philadelphia, o hacerlas prescindiendo del horno. Puedes descubrir cómo hacer cheesecake de frutos rojos sin horno guiándote por nuestra receta de cheesecake sin horno.Y si quieres más recetas de cheesecake, en RecetasGratis tenemos más de una para satisfacer tus antojos, ¡échales un vistazo!Sube la foto de tu Receta de Cheesecake de frutos rojos",
    ingdts: "Para la base: 225 gramos de galletas , 100 gramos de mantequilla . Para el relleno: 600 gramos de queso crema tipo philadelphia , 125 gramos de azúcar , 50 mililitros de nata par montar , 1 cucharada postre de maicena , 3 huevos, Para decorar:, 200 gramos de coulis de frutos rojos o de mermelada de frutos rojos , 200 gramos de frutos rojos variados frescos",
    image: "https://t2.rg.ltmcdn.com/es/images/1/4/9/cheesecake_de_frutos_rojos_73941_600.jpg"
}
];